site_name: Undine
site_description: "Undine: A batteries-included GraphQL library for Django."

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Tutorial: tutorial.md
  - Schema: schema.md
  - Queries: queries.md
  - Mutations: mutations.md
  - Filtering: filtering.md
  - Ordering: ordering.md
  - Pagination: pagination.md
  - Subscriptions: subscriptions.md
  - Global Object IDs: global-object-ids.md
  - File Upload: file-upload.md
  - Persisted Documents: persisted-documents.md
  - Interfaces: interfaces.md
  - Unions: unions.md
  - Scalars: scalars.md
  - Directives: directives.md
  - Hacking Undine: hacking-undine.md
  - Optimizer: optimizer.md
  - Async Support: async.md
  - DataLoaders: dataloaders.md
  - Lifecycle Hooks: lifecycle-hooks.md
  - Validation Rules: validation-rules.md
  - Integrations: integrations.md
  - Settings: settings.md
  - FAQ: faq.md
  - Contributing: contributing.md

theme:
  name: readthedocs
  highlightjs: false  # Use pygments instead.

exclude_docs: |
  *.py
  snippets/*

markdown_extensions:
  pymdownx.highlight:
    anchor_linenums: true
    linenums: true
  pymdownx.inlinehilite:
  pymdownx.blocks.details:
  pymdownx.snippets:
    base_path: docs/snippets
  pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:mermaid2.fence_mermaid
  toc:
    permalink: ðŸ”—
  attr_list:
  meta:

plugins:
  - search:
  - mermaid2:
      version: 11.6.0
  - serviceWorkerUrls:
  - metaDescriptions:

extra_css:
  - css/docs.css
  - css/pygments.css

extra_javascript:
  - js/docs.js
  - service-worker.js
